"""v1_6_r1_add_product_weight

Revision ID: 0c78d7662147
Revises: b0ee245c581f
Create Date: 2025-11-20 23:26:30.481339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c78d7662147'
down_revision: Union[str, Sequence[str], None] = 'b0ee245c581f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('weight', sa.Numeric(precision=12, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'weight')
    # ### end Alembic commands ###
