"""v1_6_init_schema

Revision ID: b0ee245c581f
Revises: 
Create Date: 2025-11-19 21:58:37.424640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ee245c581f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_bundle_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_sku', sa.String(length=50), nullable=False),
    sa.Column('component_sku', sa.String(length=50), nullable=False),
    sa.Column('component_qty', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bundle_sku <> component_sku', name='ck_bundle_not_self'),
    sa.ForeignKeyConstraint(['bundle_sku'], ['product.sku'], ),
    sa.ForeignKeyConstraint(['component_sku'], ['product.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_bundle_item_bundle_sku', 'product_bundle_item', ['bundle_sku'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_product_bundle_item_component_sku', 'product_bundle_item', ['component_sku'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ux_product_bundle_item_bundle_component', 'product_bundle_item', ['bundle_sku', 'component_sku'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('product', sa.Column('is_bundle', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_bundle')
    op.drop_index('ux_product_bundle_item_bundle_component', table_name='product_bundle_item', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_product_bundle_item_component_sku', table_name='product_bundle_item', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_product_bundle_item_bundle_sku', table_name='product_bundle_item', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('product_bundle_item')
    # ### end Alembic commands ###
