"""init schema v1.6-r2

Revision ID: d32019064fc2
Revises: 
Create Date: 2025-12-05 02:23:26.518609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32019064fc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('inbound_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inbound_date', sa.Date(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('supplier_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inbound_header_dates', 'inbound_header', ['inbound_date', 'order_date'], unique=False)
    op.create_index('idx_inbound_header_status', 'inbound_header', ['status'], unique=False)
    op.create_table('outbound_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outbound_date', sa.Date(), nullable=True),
    sa.Column('order_number', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('receiver_name', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('weight_g', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbound_header_date', 'outbound_header', ['outbound_date'], unique=False)
    op.create_index('idx_outbound_header_order_number', 'outbound_header', ['order_number'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_outbound_header_status', 'outbound_header', ['status'], unique=False)
    op.create_index('ux_outbound_header_tracking_number', 'outbound_header', ['tracking_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('base_sku', sa.String(length=50), nullable=True),
    sa.Column('pack_qty', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_bundle', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_inbound_unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_inbound_date', sa.Date(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pack_qty > 0', name='ck_product_pack_qty_positive'),
    sa.ForeignKeyConstraint(['base_sku'], ['product.sku'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('idx_product_barcode', 'product', ['barcode'], unique=False)
    op.create_index('idx_product_base_sku', 'product', ['base_sku'], unique=False)
    op.create_table('settings_advanced',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'key', name='uq_settings_advanced_category_key')
    )
    op.create_table('settings_basic_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('page_size', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("theme IN ('라이트', '다크', '시스템')", name='ck_settings_basic_user_theme'),
    sa.CheckConstraint('page_size BETWEEN 10 AND 200', name='ck_settings_basic_user_page_size'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'user'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('inbound_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['header_id'], ['inbound_header.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku'], ['product.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inbound_item_header_id', 'inbound_item', ['header_id'], unique=False)
    op.create_index('idx_inbound_item_sku', 'inbound_item', ['sku'], unique=False)
    op.create_table('inventory_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('qty_in', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('qty_out', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku'], ['product.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_ledger_created_at', 'inventory_ledger', ['created_at'], unique=False)
    op.create_index('idx_inventory_ledger_sku', 'inventory_ledger', ['sku'], unique=False)
    op.create_table('outbound_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('scanned_qty', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sales_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sales_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['header_id'], ['outbound_header.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku'], ['product.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbound_item_header_id', 'outbound_item', ['header_id'], unique=False)
    op.create_index('idx_outbound_item_sku', 'outbound_item', ['sku'], unique=False)
    op.create_table('product_bundle_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_sku', sa.String(length=50), nullable=False),
    sa.Column('component_sku', sa.String(length=50), nullable=False),
    sa.Column('component_qty', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bundle_sku <> component_sku', name='ck_bundle_not_self'),
    sa.CheckConstraint('component_qty > 0', name='ck_bundle_component_qty_positive'),
    sa.ForeignKeyConstraint(['bundle_sku'], ['product.sku'], ),
    sa.ForeignKeyConstraint(['component_sku'], ['product.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_bundle_item_bundle_sku', 'product_bundle_item', ['bundle_sku'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_product_bundle_item_component_sku', 'product_bundle_item', ['component_sku'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ux_product_bundle_item_bundle_component', 'product_bundle_item', ['bundle_sku', 'component_sku'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('stock_current',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('qty_on_hand', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('qty_reserved', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('qty_pending_out', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku'], ['product.sku'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_current')
    op.drop_index('ux_product_bundle_item_bundle_component', table_name='product_bundle_item', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_product_bundle_item_component_sku', table_name='product_bundle_item', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_product_bundle_item_bundle_sku', table_name='product_bundle_item', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('product_bundle_item')
    op.drop_index('idx_outbound_item_sku', table_name='outbound_item')
    op.drop_index('idx_outbound_item_header_id', table_name='outbound_item')
    op.drop_table('outbound_item')
    op.drop_index('idx_inventory_ledger_sku', table_name='inventory_ledger')
    op.drop_index('idx_inventory_ledger_created_at', table_name='inventory_ledger')
    op.drop_table('inventory_ledger')
    op.drop_index('idx_inbound_item_sku', table_name='inbound_item')
    op.drop_index('idx_inbound_item_header_id', table_name='inbound_item')
    op.drop_table('inbound_item')
    op.drop_table('users')
    op.drop_table('settings_basic_user')
    op.drop_table('settings_advanced')
    op.drop_index('idx_product_base_sku', table_name='product')
    op.drop_index('idx_product_barcode', table_name='product')
    op.drop_table('product')
    op.drop_index('ux_outbound_header_tracking_number', table_name='outbound_header', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_outbound_header_status', table_name='outbound_header')
    op.drop_index('idx_outbound_header_order_number', table_name='outbound_header', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_outbound_header_date', table_name='outbound_header')
    op.drop_table('outbound_header')
    op.drop_index('idx_inbound_header_status', table_name='inbound_header')
    op.drop_index('idx_inbound_header_dates', table_name='inbound_header')
    op.drop_table('inbound_header')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
