onlyBuiltDependencies:
  - '@carbon/colors'
  - '@carbon/feature-flags'
  - '@carbon/grid'
  - '@carbon/icon-helpers'
  - '@carbon/icons-react'
  - '@carbon/layout'
  - '@carbon/motion'
  - '@carbon/react'
  - '@carbon/styles'
  - '@carbon/themes'
  - '@carbon/type'
  - '@carbon/utilities'
  - '@ibm/plex-mono'
  - '@ibm/plex-sans'
  - '@ibm/plex-sans-arabic'
  - '@ibm/plex-sans-devanagari'
  - '@ibm/plex-sans-hebrew'
  - '@ibm/plex-sans-thai'
  - '@ibm/plex-sans-thai-looped'
  - '@ibm/plex-serif'
  - '@parcel/watcher'
  - esbuild
